server:
  port: "8080"

database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "your_password_here"
  name: "offermatrix"

jwt:
  secret: "your-jwt-secret-key-here"
  expire_hour: 168
